### ISSUE TITLE
Any any/all/race/some functions are provided?

### ISSUE THREAD

**Issue by shtse8** [plvhx/promise#1]
I am switching to this Promise from React Promise. But I don't know how to do it if I want to wait all promised to be resolved.

**Comment by plvhx** [comment]
now, i'm working on wait method. temporarily my implementation just can resolve fulfilled and rejected promise according to the Promise/A+ conformance. next, i will add cancellation method and synchronous wait support.

thanks in advance for this question.

**Comment by plvhx** [comment]
sorry for the inconvenient. i'm just trying to implement this conformance and make my implementation optimized..
