### ISSUE TITLE
Adding deferred support for backward compatibility..

### ISSUE THREAD

**Issue by plvhx** [plvhx/promise#2]
for those who still depends on Promises/A conformance..

**Comment by shtse8** [comment]
I think Promises/A+ is better. 
Also, Promises/A is already implemented by ReactPHP/Promise.

**Comment by plvhx** [comment]
yes, i definitely agree with you. but, Deferred class is just a wrapper. look to the implementation if you don't mind..

https://github.com/plvhx/promise/blob/master/src/Deferred.php
